theme: jekyll-theme-cayman

# Site
title: NDNU健康日报自动填写
subtitle: ''
description: 谨纪念shh首次开源
show_downloads: true
author: Sunhh
language: zh-CN
timezone: ''


# `Follow me on GitHub` banner in the top-right corner.
github_banner:
  enable: true
  permalink: https://github.com/Shh6266/Shh6266.github.io
  title: To repositories

